#!/bin/sh

source $HOME/.config/i3blocks/base16.sh

hddtemp=$(nc 127.0.0.1 7634 | grep -Po '\d+(?=\|C\|)')

[ ! "$hddtemp" ] && exit

t_warn=40;
t_crit=50;

max=$(echo "$hddtemp" | sort -r | head -1)

echo "$max°C" # full text
echo "$max°C" # short text

# color and urgent
if [ $max -ge $t_crit ]; then
	exit 33
elif [ $max -ge $t_warn ]; then
	echo $base09
else
	echo $base0D
fi
