#!/bin/bash

source $HOME/.config/i3blocks/base16.sh

ARTIST=$(playerctl metadata xesam:albumArtist)
TRACKNAME=$(playerctl metadata xesam:title)

echo $ARTIST - $TRACKNAME
echo $ARTIST - $TRACKNAME

echo $base0A
