#!/bin/sh

source $HOME/.config/i3blocks/base16.sh

host=$(systemctl --user status pp | grep 'expect' | grep -Po '[^ ]+$')
[ ! "$host" ] && host="disconnected"

# text
echo "$host"
echo "$host"

# color
[ "$host" = "disconnected" ] && echo "$base08" || echo "$base0B"
