#!/bin/sh

source $HOME/.config/i3blocks/base16.sh

status=$(systemctl status $BLOCK_INSTANCE | grep -Po '(?<=Active: )\w+')

# long text
echo "$BLOCK_INSTANCE"

# short text
echo "$BLOCK_INSTANCE"

# color
[ "$status" = "active" ] && echo "$base0B" || echo "$base08"
