#!/usr/bin/env python
import requests, json, re

f = open('/home/asaligrama/.weather', 'r')
url = "https://api.darksky.net/forecast/" + f.readline().strip() + "/" + f.readline().strip()

weather_json = requests.get(url)
weather_json.raise_for_status()
data = json.loads(weather_json.content.decode())

icon = ""
iconname = data["currently"]["icon"]
if (iconname.find("clear-day") > -1):
    icon = ""
elif (iconname.find("clear-night") > -1):
    icon = ""
elif (iconname.find("snow") > -1):
    icon = ""
elif (iconname.find("snow") > -1 or
      iconname.find("sleet") > -1):
    icon = ""
elif (iconname.find("cloud") > -1 or
      iconname.find("wind") > -1 or
      iconname.find("fog") > -1):
    icon = ""

print(icon + " " + str(round(data["currently"]["temperature"], 1)) + " °F")
print(icon + " " + str(round(data["currently"]["temperature"], 1)) + " °F")
