#!/bin/sh

GMAIL_UNREAD=$(curl -u $(cat ~/.gmail) --silent "https://mail.google.com/mail/feed/atom" | tr -d '\n' | awk -F '<entry>' '{print NF-1}')
WMAIL_UNREAD=$(curl -u $(cat ~/.wmail) --silent "https://mail.google.com/mail/feed/atom" | tr -d '\n' | awk -F '<entry>' '{print NF-1}')

UNREAD=$(($GMAIL_UNREAD + $WMAIL_UNREAD))

if [ $UNREAD -eq 0 ]; then
  echo ""
  exit
else
  echo "%{F#b58900}  $UNREAD%{F-}"
fi
